version: '3.8'
services:
  php:
    build: ./docker/php7.4
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/docker-vhost.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: mysql:5.7
    links:
      - php
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/mysql.conf.d/bind.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
  composer:
    build: ./docker/php7.4
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['/usr/bin/composer']  
  artisan:
    build: ./docker/php7.4
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['/bin/bash', '/var/www/html/artisan']
